# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_LSH', [dirname(__file__)])
        except ImportError:
            import _LSH
            return _LSH
        if fp is not None:
            try:
                _mod = imp.load_module('_LSH', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _LSH = swig_import_helper()
    del swig_import_helper
else:
    import _LSH
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _LSH.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _LSH.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _LSH.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _LSH.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _LSH.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _LSH.SwigPyIterator_equal(self, x)

    def copy(self):
        return _LSH.SwigPyIterator_copy(self)

    def next(self):
        return _LSH.SwigPyIterator_next(self)

    def __next__(self):
        return _LSH.SwigPyIterator___next__(self)

    def previous(self):
        return _LSH.SwigPyIterator_previous(self)

    def advance(self, n):
        return _LSH.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _LSH.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _LSH.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _LSH.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _LSH.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _LSH.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _LSH.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _LSH.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class LSH(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LSH, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LSH, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _LSH.new_LSH(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def loadSetQ(self, filePath, fileSize):
        return _LSH.LSH_loadSetQ(self, filePath, fileSize)

    def loadSetN(self, filePath, fileSize):
        return _LSH.LSH_loadSetN(self, filePath, fileSize)

    def saveCandidateSet(self, filePath):
        return _LSH.LSH_saveCandidateSet(self, filePath)

    def readHashNFromMemcached(self, server, port, runId):
        return _LSH.LSH_readHashNFromMemcached(self, server, port, runId)

    def readHashNFromRedis(self, server, port, srunId):
        return _LSH.LSH_readHashNFromRedis(self, server, port, srunId)

    def saveHashNToMemcached(self, server, port, exp):
        return _LSH.LSH_saveHashNToMemcached(self, server, port, exp)

    def saveHashNToRedis(self, server, port):
        return _LSH.LSH_saveHashNToRedis(self, server, port)

    def clearHashMatrix(self):
        return _LSH.LSH_clearHashMatrix(self)

    def clear(self):
        return _LSH.LSH_clear(self)

    def clearCollisionMatrix(self):
        return _LSH.LSH_clearCollisionMatrix(self)

    def clearCandidateSet(self):
        return _LSH.LSH_clearCandidateSet(self)

    def reportStatus(self):
        return _LSH.LSH_reportStatus(self)

    def getCollisionMatrix(self):
        return _LSH.LSH_getCollisionMatrix(self)

    def getCandidateSet(self):
        return _LSH.LSH_getCandidateSet(self)

    def setUseHdfs(self, useHdfs):
        return _LSH.LSH_setUseHdfs(self, useHdfs)

    def getSetN(self):
        return _LSH.LSH_getSetN(self)

    def getSetQ(self):
        return _LSH.LSH_getSetQ(self)

    def getHashMatrixN(self):
        return _LSH.LSH_getHashMatrixN(self)

    def getHashMatrixQ(self):
        return _LSH.LSH_getHashMatrixQ(self)

    def setThreadMode(self, threadMode):
        return _LSH.LSH_setThreadMode(self, threadMode)

    def setComputeMode(self, computeMode):
        return _LSH.LSH_setComputeMode(self, computeMode)

    def setSetN(self, setN):
        return _LSH.LSH_setSetN(self, setN)

    def setSetQ(self, setQ):
        return _LSH.LSH_setSetQ(self, setQ)

    def setDefault(self):
        return _LSH.LSH_setDefault(self)
    __swig_destroy__ = _LSH.delete_LSH
    __del__ = lambda self: None
LSH_swigregister = _LSH.LSH_swigregister
LSH_swigregister(LSH)

# This file is compatible with both classic and new-style classes.


